version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge
